import type { CSSProperties } from "react";

export const authStyles = {
  page: {
    minHeight: "100vh",
    background: "#f7f8f4",
    color: "#151713",
    fontFamily: "Arial, Helvetica, sans-serif",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: 72,
    padding: "0 clamp(18px, 4vw, 48px)",
  },
  logo: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    color: "inherit",
    fontSize: 28,
    fontWeight: 800,
    lineHeight: 1,
    textDecoration: "none",
  },
  helpLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    borderRadius: 999,
    color: "#3d4439",
    fontSize: 15,
    fontWeight: 700,
    padding: "10px 12px",
    textDecoration: "none",
  },
  shell: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 360px), 1fr))",
    gap: "clamp(30px, 6vw, 88px)",
    alignItems: "center",
    width: "min(1120px, calc(100% - 48px))",
    minHeight: "calc(100vh - 72px)",
    margin: "0 auto",
    padding: "0 0 42px",
  },
  photoPanel: {
    position: "relative",
    minHeight: "clamp(320px, calc(100vh - 144px), 680px)",
    overflow: "hidden",
    borderRadius: 8,
    background: "#d7d8d0",
  },
  photo: {
    display: "block",
    width: "100%",
    height: "100%",
    minHeight: "inherit",
    objectFit: "cover",
  },
  photoShade: {
    position: "absolute",
    inset: 0,
    background:
      "linear-gradient(to top, rgba(8, 12, 9, 0.76), rgba(8, 12, 9, 0.16) 58%, transparent), linear-gradient(to right, rgba(8, 12, 9, 0.22), transparent 48%)",
  },
  photoText: {
    position: "absolute",
    right: 32,
    bottom: 32,
    left: 32,
    maxWidth: 390,
    color: "#ffffff",
  },
  photoTitle: {
    margin: 0,
    fontSize: "clamp(36px, 4vw, 58px)",
    fontWeight: 800,
    letterSpacing: 0,
    lineHeight: 0.98,
  },
  photoCopy: {
    margin: "16px 0 0",
    maxWidth: 330,
    color: "#eef4ea",
    fontSize: 15,
    fontWeight: 700,
    lineHeight: 1.45,
  },
  form: {
    width: "100%",
    maxWidth: 440,
    justifySelf: "center",
    padding: "8px 0",
  },
  heading: {
    margin: "0 0 26px",
  },
  eyebrow: {
    margin: "0 0 8px",
    color: "#4d82de",
    fontSize: 15,
    fontWeight: 800,
  },
  title: {
    margin: 0,
    color: "#11130f",
    fontSize: "clamp(34px, 4vw, 46px)",
    fontWeight: 800,
    letterSpacing: 0,
    lineHeight: 1.03,
  },
  field: {
    display: "grid",
    gap: 8,
    marginTop: 16,
    color: "#252a22",
    fontSize: 15,
    fontWeight: 800,
  },
  input: {
    boxSizing: "border-box",
    width: "100%",
    height: 50,
    border: "1px solid #d9ded2",
    borderRadius: 8,
    background: "#ffffff",
    color: "#151713",
    font: "600 16px Arial, Helvetica, sans-serif",
    outline: "none",
    padding: "0 16px",
  },
  passwordField: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    height: 50,
    border: "1px solid #d9ded2",
    borderRadius: 8,
    boxSizing: "border-box",
    background: "#ffffff",
    padding: "0 14px 0 0",
  },
  passwordInput: {
    minWidth: 0,
    flex: 1,
    height: "100%",
    border: 0,
    background: "transparent",
    color: "#151713",
    font: "600 16px Arial, Helvetica, sans-serif",
    outline: "none",
    padding: "0 16px",
  },
  formMeta: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    marginTop: 16,
    color: "#3d4439",
    fontSize: 14,
    fontWeight: 700,
  },
  remember: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
  },
  checkbox: {
    width: 16,
    height: 16,
    margin: 0,
    accentColor: "#4d82de",
  },
  link: {
    color: "#2f68c8",
    fontWeight: 800,
    textDecoration: "none",
  },
  submitButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    width: "100%",
    height: 50,
    marginTop: 28,
    border: 0,
    borderRadius: 8,
    background: "#4d82de",
    color: "#ffffff",
    cursor: "pointer",
    font: "800 17px Arial, Helvetica, sans-serif",
  },
  footerText: {
    margin: "22px 0 0",
    color: "#3d4439",
    fontSize: 16,
    fontWeight: 700,
    textAlign: "center",
  },
  terms: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    marginTop: 18,
    color: "#3d4439",
    fontSize: 14,
    fontWeight: 700,
    lineHeight: 1.35,
  },
} satisfies Record<string, CSSProperties>;
